apiVersion: v1
kind: ServiceAccount
metadata:
  name: ping-pong-server
  labels:
    app: ping-pong-server
    mode: cofide
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-server
      mode: cofide
  template:
    metadata:
      labels:
        app: ping-pong-server
        mode: cofide
    spec:
      serviceAccountName: ping-pong-server
      containers:
      - name: ping-pong-server
        image: ko://github.com/cofide/cofide-demos/workloads/ping-pong-mesh/server
        ports:
        - containerPort: 8443
---

apiVersion: v1
kind: Service
metadata:
  name: ping-pong-server
spec:
  selector:
    app: ping-pong-server
    mode: cofide
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
  type: LoadBalancer
