apiVersion: v1
kind: ServiceAccount
metadata:
  name: ping-pong-server
  namespace: "${NAMESPACE}"
  labels:
    app: ping-pong-server
    mode: cofide
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-server
  namespace: "${NAMESPACE}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-server
      mode: cofide
  template:
    metadata:
      labels:
        app: ping-pong-server
        mode: cofide
        sidecar.istio.io/inject: "true"
      annotations:
        proxy.istio.io/config: |
          proxyMetadata:
            ISTIO_META_DNS_CAPTURE: "true"
            ISTIO_META_DNS_AUTO_ALLOCATE: "true"
        inject.istio.io/templates: "sidecar,spire"
    spec:
      serviceAccountName: ping-pong-server
      containers:
      - name: ping-pong-server
        image: ${SERVER_IMAGE}
        ports:
        - containerPort: 8443
---

apiVersion: v1
kind: Service
metadata:
  name: ping-pong-server
  namespace: "${NAMESPACE}"
spec:
  selector:
    app: ping-pong-server
    mode: cofide
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
  type: LoadBalancer
