apiVersion: v1
kind: ServiceAccount
metadata:
  name: ping-pong-jwt-client
  labels:
    app: ping-pong-jwt-client
    mode: cofide
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-jwt-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-jwt-client
      mode: cofide
  template:
    metadata:
      labels:
        app: ping-pong-jwt-client
        mode: cofide
    spec:
      serviceAccountName: ping-pong-jwt-client
      containers:
        - name: ping-pong-jwt-client
          image: ghcr.io/cofide/cofide-demos/ping-pong-jwt-client:${IMAGE_TAG}
          imagePullPolicy: Never
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
          env:
            - name: PING_PONG_SERVICE_HOST
              value: "${PING_PONG_SERVER_SERVICE_HOST}"
            - name: PING_PONG_SERVICE_PORT
              value: "${PING_PONG_SERVER_SERVICE_PORT}"
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///spiffe-workload-api/spire-agent.sock
            - name: SERVER_SPIFFE_ID
              value: ${SERVER_SPIFFE_ID}
          volumeMounts:
            - name: spiffe-workload-api
              mountPath: /spiffe-workload-api
              readOnly: true
      volumes:
        - name: spiffe-workload-api
          csi:
            driver: "csi.spiffe.io"
            readOnly: true
