apiVersion: v1
kind: ServiceAccount
metadata:
  name: ping-pong-relay
  labels:
    app: ping-pong-relay
    type: exchange
---
apiVersion: v1
kind: Service
metadata:
  name: ping-pong-relay
  labels:
    app: ping-pong-relay
    type: exchange
spec:
  selector:
    app: ping-pong-relay
    type: exchange
  ports:
    - name: http
      port: 8443
      targetPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-relay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-relay
      type: exchange
  template:
    metadata:
      labels:
        app: ping-pong-relay
        type: exchange
    spec:
      serviceAccountName: ping-pong-relay
      containers:
        - name: ping-pong-relay
          image: ${COFIDE_DEMOS_IMAGE_PREFIX}ping-pong-exchange:${COFIDE_DEMOS_IMAGE_TAG}
          imagePullPolicy: ${COFIDE_DEMOS_IMAGE_PULL_POLICY}
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
          env:
            - name: PING_PONG_MODE
              value: relay
            - name: CLIENT_SPIFFE_ID
              value: ${CLIENT_SPIFFE_ID}
            - name: EXCHANGE_URL
              value: ${EXCHANGE_URL}
            - name: PING_PONG_SERVICE_HOST
              value: "${PING_PONG_SERVER_SERVICE_HOST}"
            - name: PING_PONG_SERVICE_PORT
              value: "${PING_PONG_SERVER_SERVICE_PORT}"
            - name: SERVER_SPIFFE_ID
              value: ${SERVER_SPIFFE_ID}
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///spiffe-workload-api/spire-agent.sock
          volumeMounts:
            - name: spiffe-workload-api
              mountPath: /spiffe-workload-api
              readOnly: true
      volumes:
        - name: spiffe-workload-api
          csi:
            driver: "csi.spiffe.io"
            readOnly: true
