apiVersion: v1
kind: ServiceAccount
metadata:
  name: ping-pong-client
  labels:
    app: ping-pong-client
    mode: cofide
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-client
      mode: cofide
  template:
    metadata:
      labels:
        app: ping-pong-client
        mode: cofide
    spec:
      serviceAccountName: ping-pong-client
      containers:
      - name: ping-pong-client
        image: ghcr.io/cofide/cofide-demos/ping-pong-cofide-client:${IMAGE_TAG}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
        env:
        - name: PING_PONG_SERVICE_HOST
          value: "${PING_PONG_SERVER_SERVICE_HOST}"
        - name: PING_PONG_SERVICE_PORT
          value: "${PING_PONG_SERVER_SERVICE_PORT}"
        - name: EXPERIMENTAL_XDS_SERVER_URI
          value: "${EXPERIMENTAL_XDS_SERVER_URI}"
        - name: SPIFFE_ENDPOINT_SOCKET
          value: unix:///spiffe-workload-api/spire-agent.sock
        volumeMounts:
            - name: spiffe-workload-api
              mountPath: /spiffe-workload-api
              readOnly: true      
      volumes:
      - name: spiffe-workload-api
        csi:
          driver: "csi.spiffe.io"
          readOnly: true
