apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  labels:
    app: frontend
    demo: cofide-capital
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
    demo: cofide-capital
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      demo: cofide-capital
  template:
    metadata:
      labels:
        app: frontend
        demo: cofide-capital
    spec:
      serviceAccountName: frontend
      containers:
      - name: frontend
        image: ghcr.io/cofide/cofide-demos/cofide-capital/frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: PAYMENTS_URL
          value: http://payments:8080
        - name: REDIS_ADDR
          value: redis:6379
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    demo: cofide-capital
spec:
  selector:
    app: frontend
    demo: cofide-capital
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: LoadBalancer
