apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  template:
    spec:
      containers:
      - name: payments
        env:
        - name: COFIDE_CAPITAL_VERSION
          value: v1
        - name: PAYMENTS_API_KEY
          valueFrom:
            secretKeyRef:
              name: cofide-capital-secrets
              key: payments-api-key
        - name: LEDGER_API_KEY
          valueFrom:
            secretKeyRef:
              name: cofide-capital-secrets
              key: ledger-api-key
