apiVersion: v1
kind: ServiceAccount
metadata:
  name: ping-pong-server
  labels:
    app: ping-pong-server
    mode: cofide
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-server
      mode: cofide
  template:
    metadata:
      labels:
        app: ping-pong-server
        mode: cofide
    spec:
      serviceAccountName: ping-pong-server
      containers:
      - name: ping-pong-server
        image: ko://github.com/cofide/cofide-demos/workloads/cofide-sdk/server
        ports:
        - containerPort: 8443
        volumeMounts:
            - name: spiffe-workload-api
              mountPath: /spiffe-workload-api
              readOnly: true
        env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: unix:///spiffe-workload-api/spire-agent.sock
      volumes:
      - name: spiffe-workload-api
        csi:
          driver: "csi.spiffe.io"
          readOnly: true
---

apiVersion: v1
kind: Service
metadata:
  name: ping-pong-server
spec:
  selector:
    app: ping-pong-server
    mode: cofide
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
  type: ClusterIP
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: ping-pong-client
  labels:
    app: ping-pong-client
    mode: cofide
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-client
      mode: cofide
  template:
    metadata:
      labels:
        app: ping-pong-client
        mode: cofide
    spec:
      serviceAccountName: ping-pong-client
      containers:
      - name: ping-pong-client
        image: ko://github.com/cofide/cofide-demos/workloads/cofide-sdk/client
        env:
        - name: PING_PONG_SERVICE_HOST
          value: "$(PING_PONG_SERVER_SERVICE_HOST)"
        - name: PING_PONG_SERVICE_PORT
          value: "$(PING_PONG_SERVER_SERVICE_PORT)"
        - name: SPIFFE_ENDPOINT_SOCKET
          value: unix:///spiffe-workload-api/spire-agent.sock
        volumeMounts:
            - name: spiffe-workload-api
              mountPath: /spiffe-workload-api
              readOnly: true      
      volumes:
      - name: spiffe-workload-api
        csi:
          driver: "csi.spiffe.io"
          readOnly: true
