apiVersion: v1
kind: Service
metadata:
  name: bank-client
  labels:
    app: bank-client
    {{- include "bank.labels" . | nindent 4 }}
spec:
  selector:
    app: bank-client
  ports:
    - protocol: TCP
      port: {{ .Values.client.listenPort }}
      targetPort: {{ .Values.client.listenPort }}
  type: {{ .Values.client.serviceType }}
