apiVersion: v1
kind: Service
metadata:
  name: bank-server-api
  labels:
    app: bank-server
    {{- include "bank.labels" . | nindent 4 }}
spec:
  selector:
    app: bank-server
  ports:
    - protocol: TCP
      port: {{ .Values.server.clientApiPort }}
      targetPort: {{ .Values.server.clientApiPort }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: bank-server-webhook
  labels:
    app: bank-server
    {{- include "bank.labels" . | nindent 4 }}
spec:
  selector:
    app: bank-server
  ports:
    - protocol: TCP
      port: {{ .Values.server.webhookPort }}
      targetPort: {{ .Values.server.webhookPort }}
      {{- if and (eq .Values.server.webhookServiceType "NodePort") .Values.server.webhookNodePort }}
      nodePort: {{ .Values.server.webhookNodePort }}
      {{- end }}
  type: {{ .Values.server.webhookServiceType }}
