{{- if eq .Values.authMode "static" }}
apiVersion: v1
kind: Secret
metadata:
  name: bank-client-auth
  labels:
    {{- include "bank.labels" . | nindent 4 }}
type: Opaque
stringData:
  STATIC_CLIENT_API_KEY: {{ .Values.staticAuth.clientApiKey | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: bank-server-auth
  labels:
    {{- include "bank.labels" . | nindent 4 }}
type: Opaque
stringData:
  STATIC_CLIENT_API_KEY: {{ .Values.staticAuth.clientApiKey | quote }}
  STATIC_WEBHOOK_API_KEY: {{ .Values.staticAuth.webhookApiKey | quote }}
{{- end }}
