{{- if eq .Values.authMode "static" }}
apiVersion: v1
kind: Secret
metadata:
  name: bank-static-auth
  labels:
    {{- include "bank.labels" . | nindent 4 }}
type: Opaque
stringData:
  clientApiKey: {{ .Values.staticAuth.clientApiKey | quote }}
  webhookApiKey: {{ .Values.staticAuth.webhookApiKey | quote }}
{{- end }}
