apiVersion: v1
kind: ServiceAccount
metadata:
  name: ping-pong-client
  namespace: "${NAMESPACE}"
  labels:
    app: ping-pong-client
    mode: cofide
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-client
  namespace: "${NAMESPACE}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-client
      mode: cofide
  template:
    metadata:
      labels:
        app: ping-pong-client
        mode: cofide
        spiffe.io/spire-managed-identity: "true"
        sidecar.istio.io/inject: "true"
      annotations:
        proxy.istio.io/config: |
          proxyMetadata:
            ISTIO_META_DNS_CAPTURE: "true"
            ISTIO_META_DNS_AUTO_ALLOCATE: "true"
        inject.istio.io/templates: "sidecar,spire"
    spec:
      serviceAccountName: ping-pong-client
      containers:
      - name: ping-pong-client
        image: ${CLIENT_IMAGE}
        env:
        - name: PING_PONG_SERVICE_HOST
          value: "${PING_PONG_SERVER_SERVICE_HOST}"
        - name: PING_PONG_SERVICE_PORT
          value: "${PING_PONG_SERVER_SERVICE_PORT}"
