apiVersion: v1
kind: Namespace
metadata:
  name: analytics
  labels:
    name: analytics

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis
  namespace: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analysis
  template:
    metadata:
      labels:
        app: analysis
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
      serviceAccountName: default
      containers:
        - name: analysis-container
          image: ghcr.io/cofide/cofide-demos/aws-oidc-analysis:${IMAGE_TAG}
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - name: spiffe-workload-api
              mountPath: /spiffe-workload-api
              readOnly: true
          env:
          - name: SPIFFE_ENDPOINT_SOCKET
            value: unix:///spiffe-workload-api/spire-agent.sock
          - name: CONSUMER_TRUST_DOMAIN
            value: ${CONSUMER_TRUST_DOMAIN}
          - name: CONSUMER_SERVER_ADDRESS
            value: ${CONSUMER_SERVER_ADDRESS}
          - name: CONSUMER_SPIFFE_ID
            value: ${CONSUMER_SPIFFE_ID}
          - name: ENABLE_TLS
            value: "true"
      volumes:
      - name: spiffe-workload-api
        csi:
          driver: "csi.spiffe.io"
          readOnly: true
