apiVersion: v1
kind: Namespace
metadata:
  name: analytics
  labels:
    name: analytics

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis
  namespace: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analysis
  template:
    metadata:
      labels:
        app: analysis
        spiffe.io/spire-managed-identity: "true"
        sidecar.istio.io/inject: "true"
      annotations:
        proxy.istio.io/config: |
          proxyMetadata:
            ISTIO_META_DNS_CAPTURE: "true"
            ISTIO_META_DNS_AUTO_ALLOCATE: "true"
        inject.istio.io/templates: "sidecar,spire"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
      serviceAccountName: default
      containers:
        - name: analysis-container
          image: ghcr.io/cofide/cofide-demos/aws-oidc-analysis:${IMAGE_TAG}
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
          env:
          - name: CONSUMER_SERVER_ADDRESS
            value: ${CONSUMER_SERVER_ADDRESS}
          - name: ENABLE_TLS
            value: "false"
          - name: CONSUMER_SPIFFE_ID
            value: ${CONSUMER_SPIFFE_ID}
