apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-server
      mode: legacy
  template:
    metadata:
      labels:
        app: ping-pong-server
        mode: legacy
    spec:
      containers:
      - name: ping-pong-server
        image: ko://github.com/cofide/cofide-demos/workloads/ping-pong/server
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: tls-certs
          mountPath: "/etc/certs"
          readOnly: true
      volumes:
      - name: tls-certs
        secret:
          secretName: tls-secret
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-client
      mode: legacy
  template:
    metadata:
      labels:
        app: ping-pong-client
        mode: legacy
    spec:
      containers:
      - name: ping-pong-client
        image: ko://github.com/cofide/cofide-demos/workloads/ping-pong/client
