apiVersion: v1
kind: ServiceAccount
metadata:
  name: ping-pong-server
  labels:
    app: ping-pong-server
    mode: cofide
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-server
      mode: cofide
  template:
    metadata:
      labels:
        app: ping-pong-server
        mode: cofide
        sidecar.istio.io/inject: "true"
      annotations:
        proxy.istio.io/config: |
          proxyMetadata:
            ISTIO_META_DNS_CAPTURE: "true"
            ISTIO_META_DNS_AUTO_ALLOCATE: "true"
        inject.istio.io/templates: "sidecar,spire"
    spec:
      serviceAccountName: ping-pong-server
      containers:
      - name: ping-pong-server
        image: ghcr.io/cofide/cofide-demos/ping-pong-mesh-server:latest
        imagePullPolicy: Always
        env:
        - name: PORT
          value: ":${PING_PONG_SERVER_SERVICE_PORT}"
        ports:
        - containerPort: ${PING_PONG_SERVER_SERVICE_PORT}
---

apiVersion: v1
kind: Service
metadata:
  name: ping-pong-server
spec:
  selector:
    app: ping-pong-server
    mode: cofide
  ports:
    - protocol: TCP
      port: ${PING_PONG_SERVER_SERVICE_PORT}
      targetPort: ${PING_PONG_SERVER_SERVICE_PORT}
  type: LoadBalancer
